### ISSUE TITLE
Implement deployment of smart contract upon verification of OTP

### ISSUE THREAD

**Issue by ocdbytes** [keep-starknet-strange/vault#69]
Expected Behaviour :
- User registers.
- User verifies the OTP.
- Account contract gets deployed for that particular user.

**Comment by mubarak23** [comment]
@ocdbytes i will like to take on this issue, kindly assign this to me

**Comment by mubarak23** [comment]
if i understand this issue correctly,  already on the backend codes, we have endpoint for user registration, what this issue is expected to delivered is to restructure the flow such that
1. when user register.
2. An OTP is send
3. once the OTP is verified
4. A user account is created on the DB
5.  An account smart contract for the user is deployed.

from the existing backend code, user is registered, a user record is created on the db, with out OTP verification and Account contract deployment.  @ocdbytes

**Comment by mubarak23** [comment]
once the OPT is verified and user account is is_confirmed = true, we will call the deploy contract function to deploy the user account contract

**Comment by ocdbytes** [comment]
hey @mubarak23 This issue is already assigned and I am working on it rn. You can choose any other issue and tag Lucas he will assign it to you

**Comment by mubarak23** [comment]
hmm, @LucasLvy has this issue been assign to anyone

**Comment by LucasLvy** [comment]
yeah that's done sorry
